Add circuit switching section.
ntut-xuan/ComputerNetworkingNotes pull request #4
Opened 2022-10-03 17:54 UTC by 320Jackson

2022-10-03 17:59 UTC, ntut-xuan reviewed
請評估後考慮是否修改。

2022-10-03 17:59 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +- Unnecessary store-and-forward
語言需要統一，希望是中文（除非是專有名詞）。

2022-10-03 18:28 UTC, 320Jackson commented on md/Computer Networking Notes Ch. 1.md
> +- Unnecessary store-and-forward
已修正

2022-10-04 07:20 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +  - Binomial distribution
"Binomial Distribution" -> "使用 Binomial Distribution 來進行計算"

2022-10-04 07:21 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +  - $P(\text{Total n users, at given time, k users or more transmitting simultaneously})=\displaystyle{\sum^n_{i=k} C^n_i P^i(1-P)^{n-i}}$
"概念上可以理解成多個 Binomial Distribution 的總和"
<數學式>

2022-10-04 09:34 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +- 當鏈路已滿時，拒絕新連線
"鏈路（Link Capacity）"

2022-10-04 09:35 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +- 總共 n 個用戶，於指定時間內 k 個用戶同時傳輸的機率：
"總共 $n$ 個用戶，於指定時間內 $k$ 個用戶同時傳輸的機率"

2022-10-04 09:35 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +- 總共 n 個用戶，於指定時間內 k 個用戶以上同時傳輸的機率：
"總共 $n$ 個用戶，於指定時間內 $k$ 個用戶以上同時傳輸的機率

2022-10-04 09:35 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +- 交換器沒有 queueing delay
"Queueing Delay"

2022-10-04 09:36 UTC, ntut-xuan reviewed
請評估後決定是否修改。

2022-10-06 00:21 UTC, ntut-xuan requested changes
請評估後確認是否進行修改

2022-10-06 00:21 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +    - 涵蓋於單一場所周圍（100ft內）
"100 <空格> ft＜空格＞內"

2022-10-06 00:21 UTC, ntut-xuan commented on md/Computer Networking Notes Ch. 1.md
> +​
看起來是無意間進行了 Section 以外的變更，請移除。

2022-10-12 13:04 UTC, ntut-xuan approved these changes
LGTM.

2022-10-12 13:04 UTC, merged